<div class='alert alert-info'>Importing the required libraries</div>

In [1]:
import pandas as pd
import numpy as np

<div class='alert alert-info'>Reading the Data</div>

In [2]:
df = pd.read_csv('car-sales.csv')
df.head()

     Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

<div class='alert alert-info'>Statistical Figure</div>

In [3]:
from pandas_profiling import ProfileReport

In [4]:
pf = ProfileReport(df)
pf.to_widgets()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

VBox(children=(Tab(children=(Tab(children=(GridBox(children=(VBox(children=(GridspecLayout(children=(HTML(valu…

<div class='alert alert-info'>Checking if there some missing value</div>

- Remove the missing value where Price section is missing.
- Fill `missing` in categoricalvariable and `mean` value in numerical variable

In [5]:
df.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

- Removed the missing value where Price section is missing.

In [6]:
df.dropna(subset='Price', inplace=True)
df.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

<div class='alert alert-info'>Filling missing value with Scikit-Learn.</div>

In [7]:
#importing the required model/estimators
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

#creating categorical and numerical variable list
cv = ['Make','Colour']
nv = ['Doors','Odometer (KM)', 'Price']

#creating precess
cp = SimpleImputer(strategy='constant', fill_value='missing')
np = SimpleImputer(strategy='mean')

processing = ColumnTransformer([('process1', cp, cv),
                               ('process2', np, nv)],
                               remainder='passthrough')

df_filled = processing.fit_transform(df)
df_filled

array([['Honda', 'White', 4.0, 35431.0, 15323.0],
       ['BMW', 'Blue', 5.0, 192714.0, 19943.0],
       ['Honda', 'White', 4.0, 84714.0, 28343.0],
       ...,
       ['Nissan', 'Blue', 4.0, 66604.0, 31570.0],
       ['Honda', 'White', 4.0, 215883.0, 4001.0],
       ['Toyota', 'Blue', 4.0, 248360.0, 12732.0]], dtype=object)

- Make the filled data into new DataFrame

In [8]:
df = pd.DataFrame(df_filled, columns=['Make','Colour', 'Odometer (km)', 'Doors', 'Price'])
df.head()

     Make Colour Odometer (km)     Doors    Price
0   Honda  White           4.0   35431.0  15323.0
1     BMW   Blue           5.0  192714.0  19943.0
2   Honda  White           4.0   84714.0  28343.0
3  Toyota  White           4.0  154365.0  13434.0
4  Nissan   Blue           3.0  181577.0  14043.0

- Creating Feature(X) & Labels(Y)

In [9]:
x = df.drop('Price', axis=1)
y = df.Price

<div class='alert alert-info'>Converting the categorical Data into Numerical data</div>

- as machine learning algorithms run better on numerical value

In [10]:
#importing the required model/estimators
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

model = OneHotEncoder()

#creating categorical variable list
cv2 = ['Make','Colour', 'Doors']

processing = ColumnTransformer([('Process3', model, cv2)],
                               remainder='passthrough')
df2 = processing.fit_transform(x)
df2

<950x913 sparse matrix of type '<class 'numpy.float64'>'
	with 3800 stored elements in Compressed Sparse Row format>

<div class='alert alert-info'>Making Prediction</div>

In [11]:
#importing the required model/estimators
from sklearn.ensemble  import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

model2 = RandomForestRegressor(n_estimators=250)

#splitting the data into training and testing
x_train, x_test, y_train, y_test = train_test_split(df2, y, test_size=0.25)

In [12]:
model2.fit(x_train, y_train)

RandomForestRegressor(n_estimators=250)

In [13]:
model2.score(x_test, y_test)

-0.08516819333220216

In [14]:
y_preds = model2.predict(x_test)
y_preds2 = y_preds.reshape(238,1)
y_preds2

array([[21885.764     ],
       [12177.18      ],
       [10873.924     ],
       [12761.152     ],
       [12761.152     ],
       [12177.18      ],
       [20168.238     ],
       [12641.15      ],
       [ 7865.44      ],
       [12761.152     ],
       [12500.696     ],
       [ 9783.856     ],
       [12500.696     ],
       [ 9173.036     ],
       [ 9783.856     ],
       [12641.15      ],
       [12177.18      ],
       [10231.464     ],
       [19764.66585281],
       [12500.696     ],
       [12223.63333333],
       [11348.056     ],
       [ 9228.744     ],
       [ 9173.036     ],
       [ 9677.108     ],
       [ 9783.856     ],
       [10093.60626667],
       [12177.18      ],
       [10873.924     ],
       [10093.60626667],
       [ 9677.108     ],
       [ 9783.856     ],
       [11989.864     ],
       [12223.63333333],
       [12500.696     ],
       [15930.34808095],
       [12500.696     ],
       [20168.238     ],
       [22368.92      ],
       [12177.18      ],
       [12761.152     ],
       [19259.072     ],
       [11180.884     ],
       [28084.2701    ],
       [11295.508     ],
       [12177.18      ],
       [12223.63333333],
       [ 9677.108     ],
       [11295.508     ],
       [12223.63333333],
       [11180.884     ],
       [12177.18      ],
       [11348.056     ],
       [12223.63333333],
       [12177.18      ],
       [11054.816     ],
       [12223.63333333],
       [11180.884     ],
       [12500.696     ],
       [10729.47626667],
       [27688.596     ],
       [12500.696     ],
       [10798.152     ],
       [12177.18      ],
       [12761.152     ],
       [12641.15      ],
       [ 9576.692     ],
       [12500.696     ],
       [12761.152     ],
       [10873.924     ],
       [14737.94257143],
       [12500.696     ],
       [23739.128     ],
       [10729.47626667],
       [12761.152     ],
       [22130.516     ],
       [14191.81074905],
       [11054.816     ],
       [12761.152     ],
       [12500.696     ],
       [11054.816     ],
       [23739.128     ],
       [22368.92      ],
       [ 9173.036     ],
       [10672.94      ],
       [12500.696     ],
       [12761.152     ],
       [10873.924     ],
       [12223.63333333],
       [11054.816     ],
       [11054.816     ],
       [12177.18      ],
       [11054.816     ],
       [11295.508     ],
       [14191.81074905],
       [ 9228.744     ],
       [ 9677.108     ],
       [15370.57672453],
       [12223.63333333],
       [12223.63333333],
       [12500.696     ],
       [27688.596     ],
       [11054.816     ],
       [10873.924     ],
       [12223.63333333],
       [12500.696     ],
       [12223.63333333],
       [12500.696     ],
       [12761.152     ],
       [12223.63333333],
       [10093.60626667],
       [12500.696     ],
       [12500.696     ],
       [12177.18      ],
       [10873.924     ],
       [ 8911.13866667],
       [18955.9396746 ],
       [12500.696     ],
       [10672.94      ],
       [ 9783.856     ],
       [10873.924     ],
       [12177.18      ],
       [12177.18      ],
       [12500.696     ],
       [12500.696     ],
       [12500.696     ],
       [12223.63333333],
       [15930.34808095],
       [12500.696     ],
       [12177.18      ],
       [26285.3284    ],
       [11510.608     ],
       [12223.63333333],
       [10231.464     ],
       [12761.152     ],
       [ 7925.088     ],
       [12641.15      ],
       [12641.15      ],
       [10093.60626667],
       [12177.18      ],
       [10672.94      ],
       [12223.63333333],
       [12177.18      ],
       [12500.696     ],
       [12500.696     ],
       [12177.18      ],
       [14737.94257143],
       [23739.128     ],
       [12223.63333333],
       [ 9783.856     ],
       [ 9861.056     ],
       [ 9228.744     ],
       [12761.152     ],
       [ 9677.108     ],
       [ 9228.744     ],
       [12223.63333333],
       [11054.816     ],
       [12761.152     ],
       [12500.696     ],
       [12761.152     ],
       [12177.18      ],
       [12500.696     ],
       [ 9783.856     ],
       [12500.696     ],
       [15692.984     ],
       [12223.63333333],
       [12223.63333333],
       [12223.63333333],
       [12761.152     ],
       [12500.696     ],
       [10093.60626667],
       [11510.608     ],
       [11407.966     ],
       [12223.63333333],
       [12863.678     ],
       [11180.884     ],
       [10672.94      ],
       [12761.152     ],
       [12177.18      ],
       [12500.696     ],
       [ 9783.856     ],
       [10873.924     ],
       [11180.884     ],
       [11054.816     ],
       [15270.50064805],
       [11295.508     ],
       [10729.47626667],
       [ 9783.856     ],
       [12500.696     ],
       [ 9476.64533333],
       [11420.448     ],
       [11180.884     ],
       [12500.696     ],
       [ 9228.744     ],
       [12177.18      ],
       [12223.63333333],
       [ 9677.108     ],
       [11054.816     ],
       [10672.94      ],
       [10729.47626667],
       [ 9783.856     ],
       [10729.47626667],
       [ 9228.744     ],
       [10093.60626667],
       [12761.152     ],
       [ 9471.56      ],
       [12761.152     ],
       [ 9783.856     ],
       [12177.18      ],
       [12177.18      ],
       [ 7865.44      ],
       [18681.552     ],
       [12177.18      ],
       [23398.656     ],
       [ 9476.64533333],
       [15930.34808095],
       [27688.596     ],
       [ 9783.856     ],
       [10729.47626667],
       [ 9783.856     ],
       [10231.464     ],
       [12177.18      ],
       [12761.152     ],
       [11432.37333333],
       [12177.18      ],
       [12500.696     ],
       [26285.3284    ],
       [11180.884     ],
       [12177.18      ],
       [11673.008     ],
       [10093.60626667],
       [10231.464     ],
       [10729.47626667],
       [12500.696     ],
       [11432.37333333],
       [ 9228.744     ],
       [10231.464     ],
       [ 9173.036     ]])